insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"1"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Amsterdam');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"2"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Baku');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"3"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Bangkok');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"4"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Astana');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"5"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Athens');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"6"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Barcelona');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"7"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Berlin');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"8"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Budapest');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"9"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Valencia');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"10"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Washington');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"11"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Vienna');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"12"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Venice');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"13"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Vilnius');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"14"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Vitebsk');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"15"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Havana');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"16"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Guatemala');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"17"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Hamburg');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"18"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Glasgow');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"19"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Dakar');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"20"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Dallas');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"21"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Damascus');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"22"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Delhi');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"23"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Jakarta');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"24"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Dresden');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"25"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Dublin');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"26"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Yerevan');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"27"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Geneva');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"28"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Zagreb');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"29"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Jerusalem');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"30"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Islamabad');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"31"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Cairo');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"32"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Cannes');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"33"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Karaganda');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"34"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Cologne');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"35"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Kiev');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"36"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Kyoto');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"37"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Kishinev');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"38"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Liverpool');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"39"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Lima');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"40"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Limassol');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"41"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Lisbon');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"42"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Lviv');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"43"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Luxembourg');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"44"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Madrid');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"45"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Manila');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"46"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Marseilles');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"47"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Mexico');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"48"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Milan');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"49"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Montreal');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"50"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Nicosia');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"51"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'New York');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"52"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Nairobi');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"53"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Naples');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"54"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Odessa');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"55"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Osaka');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"56"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Oslo');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"57"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Paris');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"58"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Beijing');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"59"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Potsdam');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"60"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Busan');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"61"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Prague');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"62"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Pune');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"63"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Pyongyang');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"64"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Riga');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"65"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Rio de Janeiro');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"66"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Rotterdam');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"67"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Salvador');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"68"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Samarkand');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"69"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'San Diego');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"70"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'San Paolo');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"71"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'San Francisco');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"72"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Santo Domingo');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"73"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Sevastopol');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"74"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Seoul');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"75"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Sydney');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"76"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Simferopol');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"77"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Singapore');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"78"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Salt Lake City');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"79"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Sofia');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"80"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Istanbul');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"81"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Surat');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"82"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Tallin');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"83"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Tangshan');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"84"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Tashkent');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"85"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Tbilisi');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"86"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Teheran');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"87"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Tel Aviv');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"88"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Tokyo');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"89"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Toronto');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"90"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Taegu');

insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"91"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Wuhan');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"92"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Philadelphia');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"93"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Florence');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"94"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Hanoi');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"95"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Harare');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"96"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Kharkiv');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"97"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Hiroshima');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"98"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Houston');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"99"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Zurih');
insert into post(content, header) values ('{"ops":[{"attributes":{"font":"serif"},"insert":"100"},{"attributes":{"align":"center","header":3},"insert":"\n"}]}', 'Chicago');
